### PR TITLE
use git --mirror when pushing

### PR DESCRIPTION
**Pull request by boneskull**
see https://git-scm.com/docs/git-push\#Documentation/git-push.txt---mirror

This was prompted because I force-pushed to a branch and the mirrored repo refused it.

### CODE REVIEW

**Comment by spyoungtech** [comment]
Thanks for opening this PR.

Regarding using the `--mirror` flag, I originally chose not to use this because I wasn't sure if it would be perfectly safe to do this in all cases.

My (limited) understanding is that if the Action has a shallow clone of the repo, or for any other reason does not have all the refs from the origin, using `--mirror` may erroneously cause refs to be removed on the mirrored repo. In other words, I believe in order to use the `--mirror` flag appropriately, you must clone the repository appropriately (e.g. using `git clone --mirror`) to ensure you have all the refs. Since that's out of the control of an individual Action, it seemed safer to not use `--mirror`.


I'll look into this and do some testing to confirm one way or the other. It would be nice, perhaps, if this could be configurable. I think this may be achievable by committing a `.gitconfig` file to your repo, but I'm not sure.

**Comment by boneskull** [comment]
It would seem you can't rewrite history (use force-pushes) *without* removing refs, right?  To me, this is what "mirror" implies.

Either way, if a user wants to restrict force-pushes, that can be controlled at the branch level.

**Comment by artob** [comment]
I encountered the same issue with force-pushes not updating the destination mirror, which then leaves the workflow in a broken state until manually force-pushing to the destination.

I'd suggest that a safe `git push` flag to add would be `--force`, which would ensure pushes always work, regardless of any larger concerns regarding which refs exist where.

**Comment by spyoungtech** [comment]
Thanks all. New version is now compatible with GitHub Action 2.0 and now uses `--mirror` thanks to contributions from @perkoren

**Pull request closed without merging**
